version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: humansignal/ml-backend:chat-ai
    restart: always
    env_file:
      - ../../.env
    ports:
      - "9090:9090"
    volumes:
      - ./data/server:/data
